services:
  - type: web
    name: photos-client
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    plan: free